server {
    listen 80;
    client_max_body_size 0;

    location /pulp/api/ {
        proxy_pass http://pulp_api:24817;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /pulp/content/ {
        proxy_pass http://pulp_content:24816;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
