[shaman]
endpoint=https://shaman.ceph.com/api/

[pulp]
endpoint=https://pulp.apps.pok.os.sepia.ceph.com/pulp/api/v3/
pulp_username=ceph-ci-bot
pulp_password=CephCi123
tls_verify=false

; [pulp]
; endpoint=https://pulp.ceph.cpm/api/v3/
; admin_username=<admin_username>
; admin_password=<admin_password>
; pulp_username=<pulp_username>
; pulp_password=<pulp_password>
; tls_verify=false
